### ISSUE TITLE
[Help Wanted]:  I set a shortcut key for Get Suggestions and used it, but it didn't work and there were no pop ups

### ISSUE THREAD

**Issue by ZhangJinRongBlog** [intitni/CopilotForXcode#454] opened 2024-03-11 09:27 UTC
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I set a shortcut key for Get Suggestions and used it, but it didn't work and there were no pop ups. However, Get Suggestions only appear when I code it,   I want help!  
![截屏2024-03-11 17 23 16](https://github.com/intitni/CopilotForXcode/assets/39022001/9baf3cca-d8b8-47a6-8a3c-1383dcaa490c)

**Comment by ZhangJinRongBlog** [comment] 2024-03-11 09:47
This is a supplementary video, which was normal at the beginning. The buttons that use shortcut keys or menus later cannot be used anymore

https://github.com/intitni/CopilotForXcode/assets/39022001/701f21de-209e-4ad2-b55d-36ef93e4f924

**Comment by intitni** [comment] 2024-03-11 10:01
The app keeps track of the source (code and cursor position) of the latest suggestion so that it won't display a recently displayed but rejected/dismissed suggestion again. It is there to avoid an issue but I can't remember what the issue is. I will see if it's safe to remove it in the next release.

**Comment by ZhangJinRongBlog** [comment] 2024-03-12 01:17
Not only the Get Suggestions shortcut, but also the shortcut keys cannot be used to get the next and previous suggestions after obtaining the suggestions . This seems to be a very serious bug.

**Comment by intitni** [comment] 2024-03-12 04:51
- If the shortcuts are not working, but the menu does. It's an Xcode bug, please consider setting the shortcuts in [this way](https://github.com/intitni/CopilotForXcode/wiki/Frequently-Asked-Questions#q-keybindings-are-not-working)
- If the shortcuts are not working, and the menu is greyed out. It's an Xcode bug, please restart Xcode to reactivate the menu.
- Otherwise, please provide the steps to reproduce this issue.

**Comment by intitni** [comment] 2024-03-13 16:16
Yes the previous/next suggestion seems to dismiss the suggestion. It will be tracked here #457 instead.

**Comment by intitni** [comment] 2024-03-14 14:35
Released in 0.31.2

**Closed by intitni** 2024-03-14 14:35 UTC
Labels: enhancement, released
