### ISSUE TITLE
[Bug]: When editing the xcstrings file, the cpu usage is abnormal.

### ISSUE THREAD

**Issue by huangqingchao** [intitni/CopilotForXcode#569] opened 2024-08-30 03:10 UTC
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

When editing the xcstrings file, the cpu usage is abnormal. Always 100% occupied.
When I turn off the "CopilotForXcodeExtensionService" from the Accessibility Settings, the CPU occupancy rate returns to normal.

### How to reproduce the bug.

After using this extension normally, edit the xcstrings file.

### macOS version

14.5 (23F79)

### Xcode version

15.4 (15F31d)

### Copilot for Xcode version

0.33.8

**Comment by intitni** [comment] 2024-08-30 04:17
Hello, I can't seem to reproduce it. Please tell me more details:

- How large is the xcstrings file? What specific things were you doing when you saw the issue?
- If the file is large, can you reproduce it in a small xcstrings file?
- When you see the issue, please also export the spindump and share it with me.

<img width="574" alt="Screenshot 2024-08-30 at 12 13 32" src="https://github.com/user-attachments/assets/36562a07-5de6-4d9d-b64f-5339e50608bf">

**Comment by huangqingchao** [comment] 2024-09-03 09:40
> Hello, I can't seem to reproduce it. Please tell me more details:
> 
> * How large is the xcstrings file? What specific things were you doing when you saw the issue?

.xcstrings size is 96KB；I tried to reboot the computer and only opened xcode to edit the .xcstrings file.
There are only two languages ​​​​English and Chinese, Simplified in the file

> * If the file is large, can you reproduce it in a small xcstrings file?

I tried to create a .xcstrings file with only a few entries in another project, but this problem did not occur.

> * When you see the issue, please also export the spindump and share it with me.
[Spindump.txt](https://github.com/user-attachments/files/16846647/Spindump.txt)

Enable CopilotForXcodeExtensionService + Edit files other than "xcstrings"
![WX20240903-173147](https://github.com/user-attachments/assets/bd41261c-4a6d-4bfd-a7d4-aec94da9f76e)

Enable CopilotForXcodeExtensionService + Edit the "xcstrings" file
![WX20240903-173209](https://github.com/user-attachments/assets/95a8143f-8ef9-49e8-bfe6-0b9679ca75bc)

Disable CopilotForXcodeExtensionService + Edit the "xcstrings" file
![WX20240903-173339](https://github.com/user-attachments/assets/41460ebf-512d-4c2d-bb4a-756d4728cd02)

**Comment by intitni** [comment] 2024-09-03 10:18
What happens if you disable the suggestions feature for xcstrings?

<img width="349" alt="Screenshot 2024-09-03 at 18 17 49 1" src="https://github.com/user-attachments/assets/be23685f-4dbe-4d8e-b1ee-c163a87a1926">

**Comment by huangqingchao** [comment] 2024-09-04 00:42
Tried, but still the same problem.
![WechatIMG520](https://github.com/user-attachments/assets/f57ff6d5-e46b-4b8e-a2b3-0ad9a5863e26)

**Comment by intitni** [comment] 2024-09-08 09:26
I think the cause is by the seach for tab bars in Xcode.

**Comment by intitni** [comment] 2024-09-08 18:04
Released in 0.34.0 beta 3

**Comment by intitni** [comment] 2024-09-13 06:12
Released in 0.34.0

**Closed by intitni** 2024-09-13 06:12 UTC
Labels: bug, released

**Comment by huangqingchao** [comment] 2024-09-14 01:59
> Released in 0.34.0

After the update, the previous problem was not reproduced.
