### ISSUE TITLE
[Bug]:  App Not Responding when click the Service section

### ISSUE THREAD

**Issue by wuchuwuyou** [intitni/CopilotForXcode#341] opened 2023-08-18 07:25 UTC
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

A bug happened!
![Screenshot 2023-08-18 at 15 06 39](https://github.com/intitni/CopilotForXcode/assets/4858445/f73954f1-f234-41a8-b96c-3ebfc9874eb9)

### How to reproduce the bug.

1. Open the app
2. Click the Service tab

### macOS version

13.5

### Xcode version

14.1.0

### Copilot for Xcode version

0.21.2

### Node version

v20.5.1

**Comment by intitni** [comment] 2023-08-18 07:30
I can't reproduce it, can you make a scree recording?

**Comment by wuchuwuyou** [comment] 2023-08-18 08:50
Sure. Added.
[Video](https://youtu.be/5QQ7CpbKCFc)

**Comment by intitni** [comment] 2023-08-18 09:31
I have no idea what caused it. Please give this version a try and tell me about your observation.

1. Does this version freeze? If not, do you see any error?
2. Is the folder `~/Library/Application Support/com.intii.CopilotForXcode/GitHub Copilot` successfully created?
3. Turn on "Disable GitHub Copilot settings auto refresh status on appear" and try again?
4. Does the feature tab freeze?

https://github.com/intitni/CopilotForXcode/releases/download/0.21.2/test.app.zip

**Comment by wuchuwuyou** [comment] 2023-08-20 06:01
Didn't freeze when I did the 3th step.
But I get a new freeze.  
Service -> Github Copilot
When I clicked the refresh button, it's freeze

**Comment by intitni** [comment] 2023-08-20 06:48
What about the folder? Does it freeze when you install the language server?

**Comment by wuchuwuyou** [comment] 2023-08-20 06:57
Do you mean the 2nd step folder?
The folder is created. But it's empty

Does it freeze when you install the language server?
Yes, I think so

Maybe this report can help you to check.

[report.zip](https://github.com/intitni/CopilotForXcode/files/12387437/report.zip)

**Comment by intitni** [comment] 2023-08-20 08:40
The report points me to a line of code that fetches environment variables from an interactive logged in shell. I can reproduce the freeze when I run the same code in playground. Please give this version a try:

https://github.com/intitni/CopilotForXcode/releases/download/0.21.2/test2.app.zip

But the folder shouldn't be empty, it should contain an executable folder and a support folder.

**Comment by wuchuwuyou** [comment] 2023-08-20 09:01
Now, It's working.

> But the folder shouldn't be empty, it should contain an executable folder and a support folder.

Actually, the folder includes two folders, executable and support, but these are empty too.

**Comment by intitni** [comment] 2023-08-20 09:04
Great, I will release this fix in the next release, you can simply use the test2.app.zip for now, it's basically the latest release. I will keep the issue open until then.

**Comment by wuchuwuyou** [comment] 2023-08-20 09:11
Fine, When you release a new version, my current version can be directly upgraded? Or need to upgrade by manual?

**Comment by intitni** [comment] 2023-08-20 09:12
You can still use the in-app updater to update the app.

**Comment by wuchuwuyou** [comment] 2023-08-20 09:13
Great, Thanks for your all response!

**Comment by intitni** [comment] 2023-09-02 08:09
Released in 0.22.3

**Closed by intitni** 2023-09-02 08:09 UTC
Labels: bug, pending release
