### ISSUE TITLE
XPC Service hits 100% CPU and stops responding

### ISSUE THREAD

**Issue by timwredwards** [intitni/CopilotForXcode#43] opened 2023-03-11 14:25 UTC
> from maintainer:  If the app is freezing for you, please check [the 0.8.5 release](https://github.com/intitni/CopilotForXcode/releases/tag/0.8.5) 

Hi,

I'm still trying to get this to work. Suggestions start appearing, but immediately the XPC service hits 100% CPU and completely stops responding.

This happens every single time, I have no idea why. Any ideas?
<img width="321" alt="Screenshot 2023-03-11 at 2 21 18 pm" src="https://user-images.githubusercontent.com/10256125/224490057-badf2b1c-9055-4e02-990d-8bb1c8cbe6be.png">
<img width="471" alt="Screenshot 2023-03-11 at 2 24 40 pm" src="https://user-images.githubusercontent.com/10256125/224490061-42d4d17c-ddb8-46da-9d2c-b42b161a7836.png">

**Comment by intitni** [comment] 2023-03-11 14:39
Which version are you using? It's a known issue in 0.8.1 but should have been fixed in 0.8.2

**Comment by intitni** [comment] 2023-03-11 17:16
I guess it's 0.8.3 base on the screenshot.

Does it crash after stop responding? If so you can get a crash report from the Console.app. 

If not, please let me know:
- Where is the file located?
- How big is the project you are opening in Xcode? Will it freeze if you run the command on a swift playground at ~/Desktop?
- Would you mind sharing a copy of the file you were editing?

**Comment by timwredwards** [comment] 2023-03-11 22:06
> Does it happen in comment mode?

No, only floating.

> Where is the file located?

Locally

> How big is the project you are opening in Xcode? Will it freeze if you run the command on a swift playground at ~/Desktop?

Yes, it still freezes.

> Would you mind sharing a copy of the file you were editing?
It happens with every file, unfortunately.

**Comment by timwredwards** [comment] 2023-03-11 22:08
> Does it crash after stop responding? If so you can get a crash report from the Console.app.

Sadly no, it doesn't crash, it just hangs.

**Comment by intitni** [comment] 2023-03-12 01:40
I can't reproduce the bug, so I need your help to locate it. I have prepared a modified version of the app, wherein I have disabled some features that may cause the problem. I have also added a few toggles in the host app, which you can use to turn these features back on. Please turn these toggles on one by one, and then run the ‘get suggestions’ command after making each change. Once you identify the toggle that causes the app to freeze, please let me know. Thanks.
[Copilot for Xcode.app.zip](https://github.com/intitni/CopilotForXcode/files/10949822/Copilot.for.Xcode.app.zip)

**Comment by cr2s367067** [comment] 2023-03-13 04:53
<img width="864" alt="Screenshot 2023-03-13 at 9 47 36 AM" src="https://user-images.githubusercontent.com/47702598/224589979-9ce7e90b-0b27-4c79-83de-6ea2699e0bc0.png">
It seems like, real-time suggestion with floating widget will cause the app freeze.

xcode version: 14.2
copilot for Xcode version: 0.8.2

**Comment by intitni** [comment] 2023-03-13 05:15
> <img width="864" alt="Screenshot 2023-03-13 at 9 47 36 AM" src="https://user-images.githubusercontent.com/47702598/224589979-9ce7e90b-0b27-4c79-83de-6ea2699e0bc0.png">
> 
> It seems like, real-time suggestion with floating widget will cause the app freeze.
> 
> 
> 
> xcode version: 14.2
> 
> copilot for Xcode version: 0.8.2

I can't reproduce it, would you mind installing the [modified version mentioned above](https://github.com/intitni/CopilotForXcode/files/10949822/Copilot.for.Xcode.app.zip) to help me locate the bug?

It would be better if you can do a time profiling on the app.

**Comment by cr2s367067** [comment] 2023-03-13 14:15
![Screenshot 2023-03-13 at 10 09 40 PM](https://user-images.githubusercontent.com/47702598/224726730-7a2d5a4b-f633-46db-84cb-373ffcdbc59d.png)
![Screenshot 2023-03-13 at 10 06 04 PM](https://user-images.githubusercontent.com/47702598/224726749-e28b2f06-40af-4346-9194-c391e43a4acb.png)
![Screenshot 2023-03-13 at 10 05 25 PM](https://user-images.githubusercontent.com/47702598/224726757-662985ce-340a-48d4-a931-84197d2f0a73.png)
![Screenshot 2023-03-13 at 9 54 54 PM](https://user-images.githubusercontent.com/47702598/224726761-e31c7128-118d-4257-81e5-7aec9a6556ab.png)
![Screenshot 2023-03-13 at 9 56 40 PM](https://user-images.githubusercontent.com/47702598/224726767-2d5a500e-7a89-439c-ac65-5df4a383463f.png)
![Screenshot 2023-03-13 at 9 57 49 PM](https://user-images.githubusercontent.com/47702598/224726771-c097ab19-85a0-406e-a13b-1a09b8745bf1.png)
![Screenshot 2023-03-13 at 9 58 52 PM](https://user-images.githubusercontent.com/47702598/224726775-d37428a4-28aa-4d5a-a03d-b16a425c2291.png)
![Screenshot 2023-03-13 at 10 03 04 PM](https://user-images.githubusercontent.com/47702598/224726779-6456f7ff-150d-490b-a4f2-f3044561c2a6.png)
![Screenshot 2023-03-13 at 10 04 45 PM](https://user-images.githubusercontent.com/47702598/224726786-7a2a4111-263e-4a3a-af1f-6337839a8114.png)

The pictures above are a combination of the toggles, it looks like the suggestion panel and syntax highlighting will cause the freeze. I would love to keep testing it when I get free.

**Comment by intitni** [comment] 2023-03-13 14:19
@cr2s367067 Do you mean all these combinations can cause freeze?

**Comment by timwredwards** [comment] 2023-03-13 14:52
> Turn every toggle on, but try to generate suggestions for a file that is not in Swift, for example a markdown file. Swift has its own syntax highlighter.
B:
Markdown also hangs

> Only turn off "Enable SuggestionPanelView code block". And would you mind telling me your macOS version?
It works if you disable the SuggestionPanelView code block. But it doesn't work if you only disable syntax highlighting.

So the problem is with the code block, but not the syntax highlighting.

**Comment by intitni** [comment] 2023-03-13 15:04
@timwredwards Thank you! I think we are pretty close to the real cause, I would guess it's some kind of SwiftUI bug. Here is a new version that changes the code block from LazyVGrid to VStack, and adds a new toggle to enable the code part in the code block view. Would you mind giving it a try? If it's still not working, I think I will have to make it a web view. [Copilot for Xcode.app.zip](https://github.com/intitni/CopilotForXcode/files/10958706/Copilot.for.Xcode.app.zip)

**Comment by intitni** [comment] 2023-03-13 15:11
@cr2s367067 Oops I thought it was some Apple bug fixed in 13.2.1, but looks like it's not because I am also at 13.2.1. Please also give the following version a try! Thank you.

> @timwredwards Thank you! I think we are pretty close to the real cause, I would guess it's some kind of SwiftUI bug. Here is a new version that changes the code block from LazyVGrid to VStack, and adds a new toggle to enable the code part in the code block view. Would you mind giving it a try? If it's still not working, I think I will have to make it a web view. [Copilot for Xcode.app.zip](https://github.com/intitni/CopilotForXcode/files/10958706/Copilot.for.Xcode.app.zip)

**Comment by timwredwards** [comment] 2023-03-13 15:13
> @timwredwards Thank you! I think we are pretty close to the real cause, I would guess it's some kind of SwiftUI bug. Here is a new version that changes the code block from LazyVGrid to VStack, and adds a new toggle to enable the code part in the code block view. Would you mind giving it a try? If it's still not working, I think I will have to make it a web view. [Copilot for Xcode.app.zip](https://github.com/intitni/CopilotForXcode/files/10958706/Copilot.for.Xcode.app.zip)

This seems to work, with all toggles activated! I'll keep testing and get back to you if I experience another hang.

**Comment by intitni** [comment] 2023-03-13 15:14
[Tears on my face]

**Closed** 2023-04-07 03:49 UTC
Labels: bug, maybe fixed
